### ISSUE TITLE
Rice mapping

### ISSUE THREAD

**Issue by huangduan2018** [iamquang95/MappingPaddyRice#1]
I am a college teacher in China. Rice mapping, can you give some code documents? Email: 1281099739@qq.com

**Comment by iamquang95** [comment]
Sorry, i couldn't give you any documentation since it was our third year project at university and i stopped to follow this topic for a long time.

**Comment by huangduan2018** [comment]
Thank you very much. I think there are two algorithms（ThresholdAlgo、SVMAlgo） involved in this, right? I don't quite understand what data (quang.h5) you are using here?AddBandToHdfFile.py-->filename = "HdfFiles/**quang.h5**"

**Comment by ducnx** [comment]
Yes, there are two algorithms. ThresholdAlgo uses predefined thresholds (from a paper but I don't remember which one) to classify square area as rice paddy field or not. SVMAlgo uses SVM algorithm.
The H5 file is converted from HDF file (I guess it is better for later processing). Basically for each square area, we have features like NDVI, LSWI and label (0 or 1).

**Comment by huangduan2018** [comment]
Thank you very much for your explanation. Hope to have more communication opportunities in the future.

**Comment by iamquang95** [comment]
Thank guys, i will close this issue 👏
